/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DownloadHistoryService } from "../downloadHistory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DownloadHistoryCreateInput } from "./DownloadHistoryCreateInput";
import { DownloadHistory } from "./DownloadHistory";
import { DownloadHistoryFindManyArgs } from "./DownloadHistoryFindManyArgs";
import { DownloadHistoryWhereUniqueInput } from "./DownloadHistoryWhereUniqueInput";
import { DownloadHistoryUpdateInput } from "./DownloadHistoryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DownloadHistoryControllerBase {
  constructor(
    protected readonly service: DownloadHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DownloadHistory })
  @nestAccessControl.UseRoles({
    resource: "DownloadHistory",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDownloadHistory(
    @common.Body() data: DownloadHistoryCreateInput
  ): Promise<DownloadHistory> {
    return await this.service.createDownloadHistory({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        downloadedAt: true,
        id: true,
        quality: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        videoUrl: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DownloadHistory] })
  @ApiNestedQuery(DownloadHistoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DownloadHistory",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async downloadHistories(
    @common.Req() request: Request
  ): Promise<DownloadHistory[]> {
    const args = plainToClass(DownloadHistoryFindManyArgs, request.query);
    return this.service.downloadHistories({
      ...args,
      select: {
        createdAt: true,
        downloadedAt: true,
        id: true,
        quality: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        videoUrl: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DownloadHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DownloadHistory",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async downloadHistory(
    @common.Param() params: DownloadHistoryWhereUniqueInput
  ): Promise<DownloadHistory | null> {
    const result = await this.service.downloadHistory({
      where: params,
      select: {
        createdAt: true,
        downloadedAt: true,
        id: true,
        quality: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        videoUrl: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DownloadHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DownloadHistory",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDownloadHistory(
    @common.Param() params: DownloadHistoryWhereUniqueInput,
    @common.Body() data: DownloadHistoryUpdateInput
  ): Promise<DownloadHistory | null> {
    try {
      return await this.service.updateDownloadHistory({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          downloadedAt: true,
          id: true,
          quality: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          videoUrl: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DownloadHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DownloadHistory",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDownloadHistory(
    @common.Param() params: DownloadHistoryWhereUniqueInput
  ): Promise<DownloadHistory | null> {
    try {
      return await this.service.deleteDownloadHistory({
        where: params,
        select: {
          createdAt: true,
          downloadedAt: true,
          id: true,
          quality: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          videoUrl: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
